pull_request_rules:
  - name: queue when ready
    conditions:
      - "label=auto-merge"
      - check-success=test-python
      - check-success=typecheck-frontend
    actions:
      queue:

  - name: label stale PRs
    conditions:
      - updated-at<14 days ago
      - -closed
      - -merged
      - "-label=stale"
    actions:
      label:
        add: [stale]

  - name: close stale PRs
    conditions:
      - updated-at<30 days ago
      - -closed
      - -merged
      - "label=stale"
    actions:
      close:
        message: Closing due to 30 days of inactivity. Reopen if still needed.

queue_rules:
  - name: default
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_conditions:
      - check-success=test-python
      - check-success=typecheck-frontend
